version: "3"

networks:
  proxy:
    external: true

services:
  mysql:
    image: mysql:latest
    # volumes:
    #   - ./dbdata:/var/lib/mysql
    #   - ./dbbackup:/var/lib/mysql-db-backup
    environment:
      - "MYSQL_DATABASE=conext"
      - "MYSQL_USER=iotcms"
      - "MYSQL_PASSWORD=htactive"
      - "MYSQL_ROOT_PASSWORD=htactive"
    ports:
      - "3306:3306"
    networks:
      - proxy

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   environment:
  #     - "PMA_HOST=mysql"
  #     - "MYSQL_ROOT_PASSWORD=htactive"
  #   links:
  #     - mysql:db
  #   ports:
  #     - "81:80"
  #   networks:
  #     - web-network

  # nginx:
  #   build:
  #     context: ./nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./:/var/www
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #   networks:
  #     - web-network
  #   depends_on:
  #     - "mysql"

  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ./:/var/www/html/
    working_dir: /var/www/html
    ports:
      - "80:80"
    networks:
      - proxy
    depends_on:
      - "mysql"
